version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  backend:
    image: app
    stdin_open: true
    build: .
    command: >
      bash -c "npm run migrate-db
      && npm run watch"
    environment:
      DEV_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      NODE_ENV: development
    volumes:
      - ''
    ports:
      - '3003:3003'
    depends_on:
      - db

  frontend:
    image: app
    stdin_open: true
    working_dir: /usr/src/app/frontend
    command: npm run start
    ports:
      - '3000:3000'
    depends_on:
      - backend
